platform:
- x64
- x86

environment:
  matrix:
#
# VS 2010
#  - VS_VERSION: Visual Studio 10
#
# VS 2012
#  - VS_VERSION: Visual Studio 11
#
# VS 2013
  - VS_VERSION: Visual Studio 12

shallow_clone: true

build_script:
  - echo build_script
  - if "%platform%" == "x64" SET VS_FULL=%VS_VERSION% Win64
  - if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - if "%platform%" == "x86" SET SDK=release-1800
  - if "%platform%" == "x64" SET SDK=release-1800-x64
  - echo "%VS_FULL%"
  - set SDK_ZIP=%SDK%-dev.zip
  - set SDK_URL=http://download.gisinternals.com/sdk/downloads/%SDK_ZIP%
  - echo "%SDK_ZIP%"
  - echo "%SDK_URL%"
  - mkdir sdk
  - cd sdk
  - appveyor DownloadFile "%SDK_URL%"
  - 7z x "%SDK_ZIP%"
  - cd ..
  - set SDK_INC=../sdk/%SDK%/include
  - set SDK_LIB=../sdk/%SDK%/lib
  - mkdir build
  - cd build
  - cmake -G "%VS_FULL%" .. -DCMAKE_BUILD_TYPE=Release -DFREETYPE_INCLUDE_DIR_freetype2=%SDK_INC%/freetype -DFREETYPE_INCLUDE_DIR_ft2build=%SDK_INC%/freetype -DFREETYPE_LIBRARY=%SDK_LIB%/freetype2411.lib
  - cmake --build .. --config Release

test_script:
  - echo test_script

deploy: off
