platform:
- x64
- x86

environment:
  matrix:
#
# VS 2010
#  - VS_VERSION: Visual Studio 10
#
# VS 2012
#  - VS_VERSION: Visual Studio 11
#
# VS 2013
  - VS_VERSION: Visual Studio 12

shallow_clone: true

build_script:
  - echo build_script
  - if "%platform%" == "x64" SET VS_FULL=%VS_VERSION% Win64
  - if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - echo "%VS_FULL%"
  - mkdir build
  - cd build
  - cmake -G "%VS_FULL%" .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .. --config Release

test_script:
  - echo test_script

deploy: off
